In [1]:
from bs4 import BeautifulSoup
import requests
from selenium.common.exceptions import NoSuchElementException

import pandas as pd
pd.options.mode.chained_assignment = None

In [2]:
from selenium import webdriver
from bs4 import BeautifulSoup

In [3]:
chromedriver = r'C:\Users\keshiah\Desktop\chromedriver'
options = webdriver.ChromeOptions()
options.add_argument('headless')  
driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=options)

<ipython-input-3-204a2d50fcc5>:4: DeprecationWarning: use options instead of chrome_options
  driver = webdriver.Chrome(executable_path=chromedriver, chrome_options=options)

In [4]:
driver.get('https://wincuptt.com/schedule/')

In [5]:
df = pd.DataFrame(columns=['date','time','room','player_1','player_2','result',
                           'player_1_set','player_2_set','player_1_winner','player_2_winner',
                          'player_1_set_1_pts','player_2_set_1_pts','player_1_set_2_pts','player_2_set_2_pts',
                          'player_1_set_3_pts','player_2_set_3_pts','player_1_set_4_pts','player_2_set_4_pts','player_1_set_5_pts','player_2_set_5_pts']
                          )

In [6]:
games=driver.find_elements_by_tag_name("li")

for x in games:
    try:
        if x.find_element_by_class_name("st-result").get_attribute('textContent')!='\u00a0' and x.find_element_by_class_name("st-result").get_attribute('textContent')!=':':
            dict={
            'time':x.find_element_by_class_name("st-time").get_attribute('textContent'),
            'room':x.find_element_by_class_name("st-room").get_attribute('textContent'),
            'result':x.find_element_by_class_name("st-result").get_attribute('textContent')}
            
            names=x.find_elements_by_class_name("st-player")
            counter=1
            for name in names:
                dict['player_'+str(counter)]=name.get_attribute('textContent')
                counter+=1
        

            df = df.append(dict,ignore_index=True)
    except NoSuchElementException:
            pass

driver.quit()

In [7]:
df

,time,room,player_1,player_2,result,player_1_set,player_2_set,player_1_winner,player_2_winner,player_1_set_1_pts,player_2_set_1_pts,player_1_set_2_pts,player_2_set_2_pts,player_1_set_3_pts,player_2_set_3_pts,player_1_set_4_pts,player_2_set_4_pts,player_1_set_5_pts,player_2_set_5_pts
0,08:30,№1,Братухин Юрий,Панин Вячеслав,"3:2(11-4, 3-11, 11-7, 8-11, 15-13)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,09:00,№1,Дьяков Владимир,Панин Вячеслав,"2:3(12-10, 5-11, 11-9, 6-11, 5-11)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,09:30,№1,Братухин Юрий,Назаров Антон,"2:3(11-8, 13-11, 12-14, 9-11, 9-11)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10:00,№1,Дьяков Владимир,Назаров Антон,"3:1(2-11, 11-8, 11-2, 11-8)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10:30,№1,Братухин Юрий,Дьяков Владимир,"1:3(6-11, 12-10, 2-11, 8-11)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,11:30,№5,Кибка Евгений,Кирсанов Константин,"3:1(11-8, 7-11, 11-6, 11-8)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,12:00,№5,Кибка Евгений,Плишило Владимир,"2:3(11-4, 14-12, 7-11, 10-12, 8-11)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,12:30,№5,Данилюк Назар,Кирсанов Константин,"3:2(6-11, 7-11, 11-7, 11-4, 11-2)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,13:00,№5,Кирсанов Константин,Плишило Владимир,"1:3(11-8, 9-11, 7-11, 7-11)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,13:30,№5,Данилюк Назар,Кибка Евгений,"3:0(11-8, 11-9, 11-7)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import re
result = re.match(r'.:.',df['result'][0])
result.group(0)

res=re.findall(r'\d+-\d+',df['result'][0])

In [9]:
for row in range(len(df)):
    try:
        df['room'][row]=int(df['room'][row][-1])
    except IndexError:
        df.drop([row])
        
    
    
for row in range(len(df)):
    total_result = re.match(r'.:.',df['result'].loc[row])[0]
    df['player_1_set'][row] = int(total_result[0])
    df['player_2_set'][row] = int(total_result[-1])

In [10]:
for row in range(len(df)):   
    if df['player_1_set'].loc[row] > df['player_2_set'].loc[row]: 
        df['player_1_winner'][row]=1
        df['player_2_winner'][row]=0
    else:
        df['player_1_winner'][row]=0
        df['player_2_winner'][row]=1

In [11]:
for row in range(len(df)): 
    set_results=re.findall(r'\d+-\d+',df['result'][row])
    for set in range(5):
        try:
            df['player_1_set_'+str(set+1)+'_pts'][row]=re.findall(r'\d+',set_results[set])[0]
            df['player_2_set_'+str(set+1)+'_pts'][row]=re.findall(r'\d+',set_results[set])[1]
        except IndexError:
            df['player_1_set_'+str(set+1)+'_pts'][row]=0
            df['player_2_set_'+str(set+1)+'_pts'][row]=0

In [15]:
df=df.drop(['result'],axis=1)

In [18]:
df.date=[1]

<ipython-input-18-4ff8b29e7aa9>:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.date=[1]